/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myPackage;

/**
 *
 * @author Osikani Israel
 */
public class main_form extends javax.swing.JFrame {

     /**
      * Creates new form main_form
      */
     public main_form() {
          initComponents();
          
          pnl_parent.setVisible(false);
     }

     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          btn_red = new javax.swing.JButton();
          btn_yellow = new javax.swing.JButton();
          btn_blue = new javax.swing.JButton();
          pnl_parent = new javax.swing.JPanel();
          pnl_yellow = new javax.swing.JPanel();
          pnl_red = new javax.swing.JPanel();
          pnl_blue = new javax.swing.JPanel();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
          getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

          btn_red.setText("Red");
          btn_red.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btn_redActionPerformed(evt);
               }
          });
          getContentPane().add(btn_red, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 60, 80));

          btn_yellow.setText("Yellow");
          btn_yellow.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btn_yellowActionPerformed(evt);
               }
          });
          getContentPane().add(btn_yellow, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 60, 80));

          btn_blue.setText("Blue");
          btn_blue.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btn_blueActionPerformed(evt);
               }
          });
          getContentPane().add(btn_blue, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 60, 80));

          pnl_parent.setForeground(new java.awt.Color(255, 255, 0));
          pnl_parent.setLayout(new java.awt.CardLayout());

          pnl_yellow.setBackground(new java.awt.Color(255, 255, 0));

          javax.swing.GroupLayout pnl_yellowLayout = new javax.swing.GroupLayout(pnl_yellow);
          pnl_yellow.setLayout(pnl_yellowLayout);
          pnl_yellowLayout.setHorizontalGroup(
               pnl_yellowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGap(0, 520, Short.MAX_VALUE)
          );
          pnl_yellowLayout.setVerticalGroup(
               pnl_yellowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGap(0, 390, Short.MAX_VALUE)
          );

          pnl_parent.add(pnl_yellow, "card2");

          pnl_red.setBackground(new java.awt.Color(255, 0, 0));

          javax.swing.GroupLayout pnl_redLayout = new javax.swing.GroupLayout(pnl_red);
          pnl_red.setLayout(pnl_redLayout);
          pnl_redLayout.setHorizontalGroup(
               pnl_redLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGap(0, 520, Short.MAX_VALUE)
          );
          pnl_redLayout.setVerticalGroup(
               pnl_redLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGap(0, 390, Short.MAX_VALUE)
          );

          pnl_parent.add(pnl_red, "card3");

          pnl_blue.setBackground(new java.awt.Color(0, 0, 153));

          javax.swing.GroupLayout pnl_blueLayout = new javax.swing.GroupLayout(pnl_blue);
          pnl_blue.setLayout(pnl_blueLayout);
          pnl_blueLayout.setHorizontalGroup(
               pnl_blueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGap(0, 520, Short.MAX_VALUE)
          );
          pnl_blueLayout.setVerticalGroup(
               pnl_blueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGap(0, 390, Short.MAX_VALUE)
          );

          pnl_parent.add(pnl_blue, "card4");

          getContentPane().add(pnl_parent, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 520, 390));

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void btn_blueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_blueActionPerformed
          // TODO add your handling code here:
          pnl_parent.setVisible(true);
          pnl_parent.removeAll();
          pnl_parent.repaint();
          pnl_parent.revalidate();
          
          pnl_parent.add(pnl_blue);
           pnl_parent.repaint();
          pnl_parent.revalidate();
          
         
     }//GEN-LAST:event_btn_blueActionPerformed

     private void btn_redActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_redActionPerformed
          // TODO add your handling code here:
     pnl_parent.setVisible(true);
          pnl_parent.removeAll();
          pnl_parent.repaint();
          pnl_parent.revalidate();
          
          pnl_parent.add(pnl_red);
           pnl_parent.repaint();
          pnl_parent.revalidate();
     }//GEN-LAST:event_btn_redActionPerformed

     private void btn_yellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_yellowActionPerformed
          // TODO add your handling code here:
         pnl_parent.setVisible(true);
          pnl_parent.removeAll();
          pnl_parent.repaint();
          pnl_parent.revalidate();
          
          pnl_parent.add(pnl_yellow);
           pnl_parent.repaint();
          pnl_parent.revalidate();
     }//GEN-LAST:event_btn_yellowActionPerformed

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
          /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex) {
               java.util.logging.Logger.getLogger(main_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex) {
               java.util.logging.Logger.getLogger(main_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex) {
               java.util.logging.Logger.getLogger(main_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex) {
               java.util.logging.Logger.getLogger(main_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>

          /* Create and display the form */
          java.awt.EventQueue.invokeLater(new Runnable() {
               public void run() {
                    new main_form().setVisible(true);
               }
          });
     }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton btn_blue;
     private javax.swing.JButton btn_red;
     private javax.swing.JButton btn_yellow;
     private javax.swing.JPanel pnl_blue;
     private javax.swing.JPanel pnl_parent;
     private javax.swing.JPanel pnl_red;
     private javax.swing.JPanel pnl_yellow;
     // End of variables declaration//GEN-END:variables
}
